---

- name: Get Docker Convenience Script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: "./get-docker.sh"
    mode: 744

- name: Run Docker Install Script
  ansible.builtin.command: sudo sh ./get-docker.sh --dry-run

- name: Cleanup
  ansible.builtin.file:
    name: "./get-docker.sh"
    state: absent