name: Build and Test
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: | 
            - ghcr.io/${{ github.repository_owner }}/buildserver:latest
            - ghcr.io/${{ github.repository_owner }}/buildserver:alpha
