name: Deploy App
on:
  push:
env:
  host_addr: "54.237.4.76"
jobs:
  # provision:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       # run: echo "Hello Provisioning Infra with Terraform!"
  #       uses: actions/checkout@v5
  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v3

  #     - id: init
  #       run: cd ./terraform && terraform init
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Install Ansible
        uses: ./.github/actions/setup-ansible
      - name: Bootstrap Server
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False && cd ./ansible/bs_deployment \
          && ansible-playbook bootstrap_vm.yml
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: configure
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v5
  #     - name: Install Ansible
  #       uses: ./.github/actions/setup-ansible
  #     - name: deploy application
  #       run: echo running ansible-playbook deploy_app