name: Deploy
on:
  push:
jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        # run: echo "Hello Provisioning Infra with Terraform!"
        uses: actions/checkout@v5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # - id: init
      #   run: cd ../terraform && terraform init

      # - run: echo ${{ steps.init.outputs.stdout }}
      # - run: echo ${{ steps.init.outputs.sterr }}
      # - run: echo ${{ steps.init.outputs.exitcode }}
  configure:
    runs-on: ubuntu-latest
    needs: provision
    steps:
      - name: Yo
        run: echo yo\ngurt
  deploy:
    runs-on: ubuntu-latest
    needs: configure
    steps:
      - name: deploy application
        run: echo running ansible-playbook deploy_app