name: Deploy
on:
  push:
jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Provision Infra
        run: echo "Hello Provisioning Infra with Terraform!"
  configure:
    runs-on: ubuntu-latest
    needs: provision
    steps:
      - name: Yo
        run: echo yo\ngurt
  deploy:
    runs-on: ubuntu-latest
    needs: configure
    steps:
      - name: deploy application
        run: echo running ansible-playbook deploy_app